parameters: {}
environment: {}
packages:
  - name: whatsapp
    shared: false
    environment: {}
    parameters: {}
    annotations: {}
    functions:
    - name: webhook
      binary: false
      main: ""
      runtime: python:3.9
      web: true
      webSecure: false
      parameters: {}
      environment:
        VERIFICATION_TOKEN: "${VERIFICATION_TOKEN}"
        PAPERTRAIL_TOKEN: "${PAPERTRAIL_TOKEN}"
        GRAPH_API_TOKEN: "${GRAPH_API_TOKEN}"
        OPENAI_API_KEY: "${OPENAI_API_KEY}"
        MS_SPEECH_REGION: "${MS_SPEECH_REGION}"
        MS_SPEECH_KEY: "${MS_SPEECH_KEY}"
        MS_VISION_KEY: "${MS_VISION_KEY}"
        MS_VISION_ENDPOINT: "${MS_VISION_ENDPOINT}"
        SYSLOG_HOST: "${SYSLOG_HOST}"
        SYSLOG_PORT: "${SYSLOG_PORT}"
      annotations: {}
      limits:
        timeout: 30000