parameters: {}
environment: {}
packages:
  - name: whatsapp
    shared: false
    parameters: {}
    environment:
      PAPERTRAIL_TOKEN: "${PAPERTRAIL_TOKEN}"
      LOG_DESTINATIONS: '[{"papertrail":{"token":"${PAPERTRAIL_TOKEN}"}}]'
      SYSLOG_HOST: "${SYSLOG_HOST}"
      SYSLOG_PORT: "${SYSLOG_PORT}"
      SPACES_ENDPOINT: "${SPACES_ENDPOINT}"
      SPACES_NAME: "${SPACES_NAME}"
      SPACES_KEY: "${SPACES_KEY}"
      SPACES_SECRET: "${SPACES_SECRET}"
    annotations: {}
    functions:
    - name: webhook
      binary: false
      main: ""
      runtime: python:3.11
      web: true
      webSecure: false
      parameters: {}
      environment:
        VERIFICATION_TOKEN: "${VERIFICATION_TOKEN}"
        GRAPH_API_TOKEN: "${GRAPH_API_TOKEN}"
        OPENAI_API_KEY: "${OPENAI_API_KEY}"
        MS_SPEECH_REGION: "${MS_SPEECH_REGION}"
        MS_SPEECH_KEY: "${MS_SPEECH_KEY}"
        MS_VISION_KEY: "${MS_VISION_KEY}"
        MS_VISION_ENDPOINT: "${MS_VISION_ENDPOINT}"
        REDIS_HOST: "${REDIS_HOST}"
        REDIS_PORT: "${REDIS_PORT}"
        REDIS_PASSWORD: "${REDIS_PASSWORD}"
        FUNCTIONS_ENDPOINT: "${FUNCTIONS_ENDPOINT}"
        FUNCTIONS_NAMESPACE: "${FUNCTIONS_NAMESPACE}"
        ASCII_ART_API_SECRET: "${ASCII_ART_API_SECRET}"
      annotations: {}
      limits:
        timeout: 30000
    - name: aic
      binary: false
      main: ""
      runtime: go:1.20
      web: true
      webSecure: false
      parameters: {}
      environment: {}
      annotations: {}
      limits:
        timeout: 30000