name: CD to DO Functions
run-name: ${{ github.actor }} is deploying to DO Functions
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: deploy to dev
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: curl -sfS https://dotenvx.sh/install.sh | sh
      - run: doctl serverless install
      - run: doctl serverless connect ${{ secrets.DIGITALOCEAN_FUNCTIONS_NAMESPACE }}
      - run: dotenvx run -- doctl serverless deploy . --remote-build
        env:
          DOTENV_PRIVATE_KEY: ${{ secrets.DOTENV_PRIVATE_KEY }}
